# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c3227ab8569c7b17b1db4e9b63e1fdc1827a0c78bfa8869db83c6d5a775529bcab986b1e832f53b73d0ad39aae1273d07ac6d513151209e9925e05b6cde4bde

test:
  secret_key_base: dd8bf32957ca7cce827b98e970c34f8b753f42dabafc17478515809ca626eba8b7db5476426a41ed927901349564eaefd17d43d5bffbff8da9fcd7cd89ae1152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
